basePath: /
definitions:
  main.Micropost:
    properties:
      created_at:
        type: string
      id:
        type: integer
      title:
        example: マイクロポストのタイトル
        type: string
      updated_at:
        type: string
    required:
    - title
    type: object
  main.User:
    properties:
      avatar_path:
        example: /avatars/default.png
        type: string
      email:
        example: user@example.com
        type: string
      id:
        type: integer
      password:
        example: password123
        minLength: 6
        type: string
      role:
        example: user
        type: string
    required:
    - email
    - password
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sample server.
  title: API
  version: "1.0"
paths:
  /api/v1/auth/login:
    post:
      consumes:
      - application/json
      description: Login user with the given email and password
      parameters:
      - description: User object
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/main.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.User'
      summary: Login user
      tags:
      - auth
  /api/v1/auth/me:
    get:
      consumes:
      - application/json
      description: get current user information from token
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.User'
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Bearer: []
      summary: Get current user
      tags:
      - auth
  /api/v1/auth/signup:
    post:
      consumes:
      - application/json
      description: Signup user with the given information
      parameters:
      - description: User object
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/main.User'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/main.User'
      summary: Signup user
      tags:
      - auth
  /api/v1/microposts:
    get:
      consumes:
      - application/json
      description: get all microposts
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.Micropost'
            type: array
      security:
      - Bearer: []
      summary: List microposts
      tags:
      - microposts
    post:
      consumes:
      - application/json
      description: Create a new micropost with the given title
      parameters:
      - description: Micropost object
        in: body
        name: micropost
        required: true
        schema:
          $ref: '#/definitions/main.Micropost'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/main.Micropost'
      security:
      - Bearer: []
      summary: Create new micropost
      tags:
      - microposts
  /api/v1/microposts/{id}:
    get:
      consumes:
      - application/json
      description: get micropost by ID
      parameters:
      - description: Micropost ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Micropost'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get micropost by ID
      tags:
      - microposts
  /api/v1/users:
    get:
      consumes:
      - application/json
      description: get all users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.User'
            type: array
      summary: List users
      tags:
      - users
  /api/v1/users/{id}:
    get:
      consumes:
      - application/json
      description: get user by ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.User'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get user by ID
      tags:
      - users
securityDefinitions:
  Bearer:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
